title: ASRY FLORIST
description: Kirim Karangan Bunga Ucapan, buket mawar segar & plastik, murah online 24 jam.
author: Asry Florist
avatar: /logo.png
email: asry.florist27@gmail.com
url: "https://m.asryflorist.com"
baseurl: # the subpath of your site, e.g. "/blog"
permalink: /:title.html
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-image-size
  - jekyll-redirect-from

paginate: 5

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
google_analytics: UA-97740878-1

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
disqus: 
  shortname: asryflorist-2

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: AsryFlorist
  card: summary
logo: logo.png
social:
  name: Asry Florist
  links:
    - https://twitter.com/asryflorist
    - https://www.facebook.com/asryflorist
    - https://github.com/bungaasryflorist
google_site_verification: wSXsbznzLNxebnIcadMDkcalqNJG6nNHJ2WGR_Tk14Q
lang: id
